### ISSUE TITLE
install fails on windows

### ISSUE THREAD

**Issue by chadbr** [arjunmehta/multiview#4]
Installing multiview on Windows 10 fails... expected?

C:\dev\git\someApp>node --version
v7.7.2

C:\dev\git\someApp>yarn --version
0.21.3

C:\dev\git\someApp>npm --version
4.1.2

C:\dev\git\someApp>yarn add multiview
yarn add v0.21.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠁ buffertools: MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix t
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
[-/1] ⠂ waiting...
error C:\dev\git\someApp\node_modules\buffertools: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\dev\git\someApp\node_modules\buffertools
Output:
C:\dev\git\someApp\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.2 | win32 | ia32
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\dev\\git\\someApp\\node_modules\\buffertools\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\chadb_000\\.node-gyp\\7.7.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\chadb_000\\.node-gyp\\7.7.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\dev\\git\\someApp\\node_modules\\buffertools',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\dev\\git\\someApp\\node_modules\\buffertools\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\dev\git\someApp\node_modules\buffertools\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\git\someApp\node_modules\buffertools
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

C:\dev\git\someApp>

**Comment by chadbr** [comment]
same happens on node 6.10.x also...

**Comment by arjunmehta** [comment]
@chadbr Thank you for this. Looks like buffertools is having issues installing on your machine. I will look into this. One of Multiview's dependencies uses buffertools. I can try updating to the latest version and see if that fixes it. Should take a day or so. Can you help me test out a new version once I put it up?

**Comment by chadbr** [comment]
Absolutely... works great on my mac

Forgot to mention I tried 64bit node also

**Comment by arjunmehta** [comment]
Awesome! Thank you. Something could help confirm this:
Can you just try in a new node project `npm install buffertools@2.1.3`

You should get the same errors.

Then try `npm install buffertools@latest`

Do you get the same errors?

**Comment by chadbr** [comment]
every version I try fails... 2.1.4, 2.1.2, 2.1.0, 2.0.0..

**Comment by chadbr** [comment]
https://github.com/bnoordhuis/node-buffertools/issues/83

**Comment by arjunmehta** [comment]
Strange. I'm not too familiar with windows at all, but it may be that you need to install the .NET framework on your system to be able to install.

Nonetheless, I am going to update multiview to use the latest modules. It's been a while anyway. :)

I will close this issue if it's apparent that it may just be a one off situation with your system (ie. not having .NET installed for node-gyp to build buffertools).

Thank you for testing buffertools installs!

**Comment by arjunmehta** [comment]
@chadbr I've used a new dependency that should not require buffertools or any gyp installation. :D

`npm install multiview@latest` 

Hope this solves the issue!

**Comment by chadbr** [comment]
Great - I'll have a look!
