### ISSUE TITLE
Running any yarn script in multiview doesn't work

### ISSUE THREAD

**Issue by raleksandar** [arjunmehta/multiview#5]
I'm trying to use multiview with yarn and I want to have this in my `"scripts"` section of `package.json`:

```js
"dev": "yarn build:dev && multiview [yarn watch] [yarn run:api] [yarn run:server]"
```

But after the `build:dev` scripts finishes (just runs webpack with dev config) multiview starts and displays `<command> (done)` and `Exited with code 1` for each command without ever running them.

I have confirmed that this is not due to webpack or nodemon (which are used in my watch and run:* tasks) by having this in my `"scripts"` section:

```js
"testmv1": "multiview [yarn lsla]",
"testmv2": "multiview [ls -la]",
"lsla": "ls -la"
```

Running `yarn testmv1` shows same behavior as my config (i.e. the `lsla` script is not executed by multiview and it reports exit code 1) while running `yarn testmv2` executes `ls -la` and displays its output correctly.

I have tested this on Windows 10 (x64, latest insider fast build) with Node v7.8.0 and Yarn v0.22.0 (which is current RC, tried first with latest stable v0.21.3 but it's the same behavior with both versions).

**Comment by arjunmehta** [comment]
@raleksandar thanks for this. Can you tell me which version of multiview you're using? Is it installed via npm?

I'm honestly not too familiar with yarn so might need a bit of help understanding the underlying mechanisms yarn employs when invoking npm installed cli programs and in that context how they invoke yarn scripts :)

Multiview should technically take the commands and spawn them but depending on how yarn is invoked globally vs locally it may fail.

In your yarn config can you try a few things:
Try: `multiview [yarn]`
Try: `multiview [yarn 'lsla']`

What happens if you call these directly from the command line?

I'll try testing on my local environment too (macOS).

**Comment by raleksandar** [comment]
Hi @arjunmehta, thanks for quick reply :)

I forgot to mention version of multiview I'm using, sorry, it's v2.5.1. I have been running it from local node_modules dir (i.e. didn't have multiview installed globally). But I have tried:

`multiview [yarn]` (after installing multiview with `yarn global add multiview`)
`multiview [yarn lsla]` 
`./node_modules/.bin/multiview [yarn]`
`./node_modules/.bin/multiview [yarn lsla]`

And they all fail to run command (they give exit code 1 instead).

I have also verified running multiview (both local and global) without having yarn involved and both of these work:

`multiview [ls -la]`
`./node_module/.bin/multiview [ls -la]`

**Comment by raleksandar** [comment]
Closed this accidentally :)

**Comment by raleksandar** [comment]
I have just tried using `npm run testmv1` instead of yarn, and I got exact same result (i.e. command not run, exit code 1 reported by multiview).

I've changed package.json to have following in scripts filed:

```js
"testmv1": "multiview [npm run lsla]",
"testmv2": "multiview [ls -la]",
"lsla": "ls -la"
```

And running `npm run testmv1` fails while `npm run testmv2` works, same as with Yarn.

So.. not sure what exactly is the problem :)

**Comment by arjunmehta** [comment]
@raleksandar It seems to be working alright on macOS.
I've created a test project with `package.json`:

```JSON
{
  "name": "yarnTest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "lsla": "ls -la",
    "mv": "multiview [yarn lsla] [yarn lsla] -x 2000"
  },
  "dependencies": {
    "multiview": "^2.5.1"
  }
}
```

Running `yarn mv` executes correctly.

So, this may be windows specific, and maybe have something to do with how node executes npm "binaries" on windows.

Will look into it some more, but this will be difficult for me to test! :(

**Comment by raleksandar** [comment]
I believe I've "fixed" it. Well, made it run `multiview [yarn lsla] [yarn lsla]` :)

I have added `"shell"` option in a call to `child_process.spawn` in `lib/Spawn.js`:

```js
var spawnedProcess = spawn(command, args, {
    shell: 'cmd.exe'
 });
```

I'll test a bit more and if it's ok with you I could create a PR which would set shell option to cmd.exe if running on windows?

**Comment by arjunmehta** [comment]
Yes please contribute a fix! Can you also test with npm in addition to yarn?
This library is sadly very difficult to test for, but your solution makes a lot of sense.

I was going to point you to this: https://github.com/nodejs/node/issues/3675

Definitely something to do with `cmd`.

**Comment by raleksandar** [comment]
Tested with both yarn and npm, also ran couple of other Node.js binaries (webpack, gulp) via multiview. Everything works :)

**Comment by arjunmehta** [comment]
Nice! I reviewed your PR. Looks excellent, but I have a few code style nits before we merge.

**Comment by arjunmehta** [comment]
@raleksandar Thank you for your help!
