### ISSUE TITLE
always fails on Windows 7

### ISSUE THREAD

**Issue by chadbr** [arjunmehta/multiview#7]
I'm not sure if this is a Windows 7 issue or not -- but any commands I try to use in multiview fail with Exit code 1

Using multiview@latest

Is this a know issue / limitation?

Thanks! Chad

**Comment by arjunmehta** [comment]
@chadbr Please look at issue https://github.com/arjunmehta/multiview/issues/5
We are working on it. @raleksandar made a PR that should fix this. But I'm looking for a CI that will test all versions of node on windows before I feel confident to push to npm.

Please feel free to clone the latest master branch and test.

**Comment by chadbr** [comment]
great - glad to hear it. Will try.

**Comment by arjunmehta** [comment]
@chadbr Have you had a chance to try?

Here are some instructions to try it:

```bash
git clone git@github.com:arjunmehta/multiview.git
cd multiview
npm install
node cli.js [ls -la]
```

Feel free to test a few commands.

**Comment by raleksandar** [comment]
Hey @arjunmehta could you possibly publish current master with a prelease tag until you figure out the CI situation? It would be great if we could install it as `multiview@2.5.2-rc1` or something like that.

I've started using multiview on two projects I'm currently working on and I had to manually apply the fix on 2 computers so far for both projects :)

**Comment by raleksandar** [comment]
@arjunmehta Excellent! Thanks! :)

**Comment by chadbr** [comment]
@arjunmehta tested `multiview@beta` on Windows - seems to be working well!

Thanks @arjunmehta & @raleksandar

**Comment by arjunmehta** [comment]
I'm going to release this. Messed up with the versioning so need to bump latest to 2.5.3 :/
Will open a new issue for windows ci.
